name: .NET 8 Back-End Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      Solution_Name: api/Univent/Univent.sln

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}
    
    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --no-restore
      
